//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace majutech.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tolist
    {
        public int id { get; set; }
        public string task { get; set; }
        public string description { get; set; }
        public string author { get; set; }
        public string responsible { get; set; }
        public bool finish { get; set; }
    }
}
